### ISSUE TITLE
Redirect url requires protocol, simple reddit.com doesn't work,

### ISSUE THREAD

**Issue by ua741** [blunderboy/requestly#33]
Following Items need to be completed

1. [x] Add validation in Redirect Rule for Source and Destination Urls
2. [x] Add same validation for Cancel Rule
3. [x] Add Unit Tests

**Comment by blunderboy** [comment]
@ua741 I have finished this task. This should be available the next time I launch Requestly into Chrome Store. Thanks for opening the issue. I am closing this one.
