### ISSUE TITLE
option for decode the final URL

### ISSUE THREAD

**Issue by okgoogle** [blunderboy/requestly#42]
I'm glad to see this extension have supported regular expression rules!
Suggest:Please add a Decode URL option, which results in the encoded characters of the final URL replaced with the corresponding ones, e.g.

http%3A%2F%2Fwww.google.com%2F to http://www.google.com/

Example：Redirect Google search tracking：
From：
/^https?:\/\/www\.google\.com\/url\?.+url=([^&]+).*/
To：(had decoded)
$1

If it redirects successfully,chrome://history/ will not see https://www.google.com/url?...

**Comment by blunderboy** [comment]
@okgoogle Thanks for opening the issue. I appreciate it!!

I apologize but I am not able to understand the use-case clearly. If I open chrome://history here it is what I see:

![selection_028](https://cloud.githubusercontent.com/assets/3108399/6632962/915a1378-c965-11e4-8047-7985c64a6a01.png)

Can you please share an example with more details. I will try my best to support this feature in near future.

**Comment by okgoogle** [comment]
Hi,you're a good man.Thanks for your reply!

We can find https://www.google.co.in/url?sa=t&rct=j...  in your screenshot. (position:last but one and last but four)

When we search something by Google,for example,to search the word "news":
https://www.google.com/search?hl=en&newwindow=1&q=news

1.We can see one of the search results is http://news.google.com/,however, when we click the link,it will visit the URL below first:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCQQFjAB&url=http%3A%2F%2Fnews.google.com%2F&ei=Eh8DVaueNI6NyATJvoFA&usg=AFQjCNEHwOOOa98L61UWwsdBnogeLwmTsA&bvm=bv.88198703,d.aWw&cad=rjt

and visit http://news.google.com/ finally. 
chrome://history will record https://www.google.com/url?...

2.We can add a regular expression rule through your extension:

From：
/^https?:\/\/www.google.com\/url\?.url=([^&]).*/
To：(had not decode，just like now)
$1

The result is:the extension redirects the URL to "http%3A%2F%2Fnews.google.com%2F",but the browser can not understand it.
As a result,it doesn't work.
chrome://history will also record https://www.google.com/url?...

A Chrome's app will help us to understand it:
https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc
Guide:open the app,Extensions-->Requestly-->Behavior-->Realtime-->Clear screen,observe it when click one of the search results.

3.If there is a option allow us to choose decoding the final URL or not,it will be much better.Of course,in this case,we will choose "decode":
From：
/^https?:\/\/www.google.com\/url\?.url=([^&]).*/
To：(had decoded)
$1

The extension will redirect the URL to "http://news.google.com/"(of course,after decoding),that's what we want! 
The Chrome's app will help us to understand it:
https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc

This time,chrome://history will not record https://www.google.com/url?...
As a result,we can save time!

**Comment by blunderboy** [comment]
@okgoogle aah!! I understand it now..You mean to say just give users an option to decode the result obtained by Regex and then make the redirect.

Great explanation though!!

Now, I am thinking in the lines of User Interface : What should be the best option to have user decode something in URL and make some action (redirec/replace) on it.

I will open an issue in the repo with more details to support this feature. Do let me know if you have something in your mind ?

Thanks!!

**Comment by blunderboy** [comment]
I have opened #43 to implement this one. 
BTW if I remember correctly I read a similar review on Chrome Extension Reviews Page asking for similar feature few days back. 
Unfortunately, that review is not there now. May be he/she removed it for some reason. 
Wondering if that was you.

**Comment by okgoogle** [comment]
Yes，I wrote a review on Chrome Extension Store Reviews Page a few days ago.I didn't remove it by myself,but it disappeared,I don't know why!

**Comment by blunderboy** [comment]
@okgoogle Oh..great..BTW Thanks for the review..No issues if it is not appearing there...I don't care much about that...I always wanted to reply to that review and wanted to understand it but there was no option by Google to contact the reviewers. Anyways!! I am closing this one as #43 will implement this one.
