### ISSUE TITLE
Do you consider to add functions like modify response header?

### ISSUE THREAD

**Issue by hackwaly** [blunderboy/requestly#48]
I'd like to use your extension to hook all request and response.

**Comment by blunderboy** [comment]
@hackwaly Modify Response Header is already there from the time Modification of headers feature was developed. 

Try to explain more. May be we are on different paths.

**Comment by hackwaly** [comment]
I'm sorry I did carelessly before I open this issue. I got it right now.
May be modify header can use regexp like replace url. Currently it seems same as add header.
Consider this case: change the mime type in Content-Type header but leave charset not change.

**Comment by blunderboy** [comment]
@hackwaly Thanks for opening the issue. I understand the use case. I will look towards working on it.
Instead of providing a regex based match, I am going to provide another method of letting users writing function in the chrome extension and executing the function based on the rule.

**Comment by hackwaly** [comment]
That will be difficult due to the CSP restriction. Chrome does not allow you to use `eval` or `new Function`. I don't know how Tampermonkey achieve it. I should learn this.

**Comment by blunderboy** [comment]
@hackwaly You are spot on the issues which will be show stoppers for this feature..
I guess eval could be done by relaxing the CSP in manifest.json. I am not sure though I need to revise my concepts.

**Comment by blunderboy** [comment]
@hackwaly I think this is a very specific use case and I do not plan to support it in near future..I am closing this issue and probably if required I will open a different issue and work on it.

Right now, with limited available to me to support this extension's development, I am thinking to close this and whenever required open a new one when I decide to work on it.

I hope you are fine with it.
