### ISSUE TITLE
URL rule in header modification can't match against fragment part

### ISSUE THREAD

**Issue by haridsv** [blunderboy/requestly#71]
I had a URL that looked like this:

https://server/proxy/monitoring/index.html?host=hbaseProxy#query

So, I entered the string "hbaseProxy#query" for Url -> Contains and it didn't work. When I changed the string to "proxy/monitoring", it worked fine. Perhaps the match is not done against the URL "fragment" part?

**Comment by blunderboy** [comment]
@haridsv The following rule seems to work for me. 
[issue-71-url-contains-fragment-test.txt](https://github.com/blunderboy/requestly/files/11373/issue-71-url-contains-fragment-test.txt)

I have attached the rule file. Please download it and import and try it out. Let me know if I did something wrong here.

**Comment by blunderboy** [comment]
@haridsv Should we close this issue if your rule is working ?

**Comment by haridsv** [comment]
Sorry about the late response, but I can see that your example works. When I tried to disable gzip compression on a page by setting Accept-Encoding to an empty value, it didn't work, as otherwise the page would have loaded fine (there was a bug in the proxy for handling gzip content, so I was trying to work around that). When I changed the matching string in the URL, it immediately worked, so I concluded that the issue was with matching fragment part. I probably made some other mistake, or concluded too soon, so please accept my apologies!

**Comment by blunderboy** [comment]
@haridsv No problems..Glad to know you sorted out the problem..Cheers!!

**Comment by haridsv** [comment]
Thank you, for looking into the issue :)
