### ISSUE TITLE
Redirect based on Request Type

### ISSUE THREAD

**Issue by offhub** [blunderboy/requestly#74]
Hi @blunderboy,

I have just started using your extension and it is awesome. It's missing the one feature that caused me to look for it though.

Ability to set request type for rules.

```
Rule: redirectbasedrule
Request Type: xhr + script
Result: it will only redirect xhr and script resources.
```

``` https://developer.chrome.com/extensions/webRequest#type-ResourceType ```

Thanks

**Comment by blunderboy** [comment]
@offhub Thanks for the suggestion. This thought crossed my mind earlier in the beginning of the development stage. Actually, in most of the cases we separate scripts, xhr with their extensions So I did not think this would make much difference.

Do you have such a use case ?
If yes, I think I have to provide some sort of Advanced functionality within a rule which should be shown only when user clicks on Advanced link. Thoughts ?

**Comment by offhub** [comment]
xhr + script was an example but it would be great if we could separate main_frame (address bar, clicking links?) with other request.

**Comment by blunderboy** [comment]
@offhub That's good suggestion indeed but I do not want to add this functionality unless I really feel the need for it or unless I get more number of requests for this.
Pardon me for not considering this suggestion.

**Comment by blunderboy** [comment]
@offhub Can we consider to close this issue ? We can consider this one later.

**Comment by offhub** [comment]
@blunderboy No problem, you can close this issue. Sorry for my late reply.
