### ISSUE TITLE
Regex acting funny

### ISSUE THREAD

**Issue by gitmanbro** [blunderboy/requestly#75]
Hi,

I'm trying to add a query string to a URL, so I match with `/(.*www\.example\.com.*)/` and then replace it with `$1\?name=value`, but it's repeating whatever I try to add at the end twice. 

e.g. It'll end up with `https://www.example.com/?name=value?name=value`

What am I doing wrong?

**Comment by offhub** [comment]
Your second ``` .* ``` matches any character zero or more times including replaced strings.

Try this:

Match:
``` /(.*www\.example\.com\/)((?:(?!\?name=value).)*)/ ```

Replace:
``` $1$2?name=value ```

**Comment by gitmanbro** [comment]
Are you saying the site is reloading itself thus re-appending the string? I'll try your example, thanks.

**Comment by blunderboy** [comment]
@gitmanbro I need to look into this. Are you trying this on some published site or some local instance ?
Can you upload/paste the screenshot of the rule you are using ?

**Comment by gitmanbro** [comment]
I'm using it on https://www.quora.com. This is the rule I was using: http://i.imgur.com/mmU6DhK.png

It doesn't matter what comes after `$1`; if I wrote `$1test` as the destination it would append `testtest` to the URL.

**Comment by blunderboy** [comment]
@gitmanbro I looked into it and figured out the following reason:

1. Your rule is executed twice. Firstly it replaces `http://www.example.com` to `http://www.example.com?name=value`
2. Finally, new url is again matched with same rule and the same parameter is again added to the url.

It is still a mystery to me why it does not end in infinite loop. Looks like a chrome logic there to prevent chrome extensions to turn request url to infinite redirects..

But your problem can be solved by using the following rule.

Url matches: `/(.*www\.example\.com[^?]*)/`
Value: `$1?name=sachin`

Please try this and let me know if it solves your problem. I have already a task open to add support for query parameters to Url. Hopefully, that should be the best approach to handle such scenarios.

**Comment by gitmanbro** [comment]
Interesting solution. It goes until it finds a question mark, right? Thanks, it works just fine.

**Comment by blunderboy** [comment]
@gitmanbro Actually, I match the url and after .com every character is accepted except `?` So `http://www.example.com` is matched with regex but `http://www.example.com?name=sachin` does not match and hence query parameter is not added again. 

Since, you are good with the suggestion, I am closing this issue.
