### ISSUE TITLE
Requestly injecting itself into unrelated <div id="content"> elements on localhost

### ISSUE THREAD

**Issue by asedeno** [blunderboy/requestly#77]
Requestly 3.5 replaces the contents of a &lt;div id="content"&gt; with itself if the page is being served from localhost (any port). That is not acceptable behavior.

**Comment by blunderboy** [comment]
@asedeno Thanks for notifying me of this issue. Actually Its my mistake I left "localhost" in manifest file when I was testing this on localhost. I'd quickly fix this.

**Comment by blunderboy** [comment]
@asedeno Actually, I put localhost entry inside manifest.json when I test things in development and when I release requestly, I always remove this entry but I forgot to remove this when I released v3.5

Anyways, I have fixed this and I have also released v3.5.1 whicih should be available to you soon.

**Comment by blunderboy** [comment]
@asedeno I'd wait for you to confirm that issue is fixed and then we'll close this issue.

**Comment by blunderboy** [comment]
@asedeno Shall we close this issue now ?

**Comment by asedeno** [comment]
Sorry, I did not notice you had been pinging me here. Yes, I just test with 3.5.1 and its looking better now. Thanks!
